//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ExpenseSystem.Entities
{
    public partial class ExpenseRecord
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual decimal Price
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateStamp
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Tag Tag
        {
            get { return _tag; }
            set
            {
                if (!ReferenceEquals(_tag, value))
                {
                    var previousValue = _tag;
                    _tag = value;
                    FixupTag(previousValue);
                }
            }
        }
        private Tag _tag;

        #endregion
        #region Association Fixup
    
        private void FixupTag(Tag previousValue)
        {
            if (previousValue != null && previousValue.ExpenseRecords.Contains(this))
            {
                previousValue.ExpenseRecords.Remove(this);
            }
    
            if (Tag != null)
            {
                if (!Tag.ExpenseRecords.Contains(this))
                {
                    Tag.ExpenseRecords.Add(this);
                }
            }
        }

        #endregion
    }
}
